/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticatedResponseRole } from './authenticatedResponseRole'

export interface AuthenticatedResponse {
  accessToken: string
  email: string
  nickname: string
  refreshToken: string
  role: AuthenticatedResponseRole
  userId: number
}
