/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type AuthResultWrapperResponseAuthResultStatus =
  (typeof AuthResultWrapperResponseAuthResultStatus)[keyof typeof AuthResultWrapperResponseAuthResultStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthResultWrapperResponseAuthResultStatus = {
  AUTHENTICATED: 'AUTHENTICATED',
  REGISTRATION_REQUIRED: 'REGISTRATION_REQUIRED',
} as const
