/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { AuthenticationResponseRole } from './authenticationResponseRole'

export interface AuthenticationResponse {
  accessToken: string
  email: string
  nickname: string
  refreshToken: string
  role: AuthenticationResponseRole
  userId: number
}
