/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface BannerResponse {
  createdAt: string
  description?: string
  endDate: string
  id: number
  imageUrl?: string
  isActive: boolean
  linkUrl: string
  startDate: string
  title: string
  updatedAt: string
}
