/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { PostResponse } from './postResponse'

export interface BasePageResponsePostResponse {
  content: PostResponse[]
  first: boolean
  last: boolean
  pageNumber: number
  pageSize: number
  totalElements: number
  totalPages: number
}
