/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export interface CategoryResponse {
  createdAt: string
  description?: string
  id: number
  isActive: boolean
  name: string
  updatedAt: string
}
