/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { OAuthInfoResponseOauthProvider } from './oAuthInfoResponseOauthProvider'

export interface OAuthInfoResponse {
  email: string
  nickname: string
  oauthProvider: OAuthInfoResponseOauthProvider
  uniqueIdentificationValue: string
}
