/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { PlantSaveResponseLocation } from './plantSaveResponseLocation'
import type { PlantSaveResponsePotType } from './plantSaveResponsePotType'

export interface PlantSaveResponse {
  id: number
  location: PlantSaveResponseLocation
  nickname: string
  plantImage: string
  plantingDate: string
  plantType: string
  potType: PlantSaveResponsePotType
}
