/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */

/**
 * @minLength 2
 * @maxLength 20
 */
export type PlantCreateRequestDtoPotType =
  (typeof PlantCreateRequestDtoPotType)[keyof typeof PlantCreateRequestDtoPotType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlantCreateRequestDtoPotType = {
  PLASTIC: 'PLASTIC',
  TERRACOTTA: 'TERRACOTTA',
  CERAMIC: 'CERAMIC',
  METAL: 'METAL',
  WOODEN: 'WOODEN',
  GLASS: 'GLASS',
  HANGING_BASKET: 'HANGING_BASKET',
  SELF_WATERING: 'SELF_WATERING',
  DECORATIVE: 'DECORATIVE',
} as const
