/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { PlantEventRequestDtoEventTypesItem } from './plantEventRequestDtoEventTypesItem'

export interface PlantEventRequestDto {
  eventDate: string
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  eventTypes: PlantEventRequestDtoEventTypesItem[]
}
