/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type PlantCreateRequestDtoLocation =
  (typeof PlantCreateRequestDtoLocation)[keyof typeof PlantCreateRequestDtoLocation]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlantCreateRequestDtoLocation = {
  KITCHEN: 'KITCHEN',
  DESK: 'DESK',
  BALCONY: 'BALCONY',
  BATHROOM: 'BATHROOM',
  OUTDOORS: 'OUTDOORS',
  OTHER: 'OTHER',
} as const
