/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type PlantEventRequestDtoEventTypesItem =
  (typeof PlantEventRequestDtoEventTypesItem)[keyof typeof PlantEventRequestDtoEventTypesItem]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlantEventRequestDtoEventTypesItem = {
  WATERING: 'WATERING',
  REPOTTING: 'REPOTTING',
  PRUNING: 'PRUNING',
  NUTRITION_MANAGEMENT: 'NUTRITION_MANAGEMENT',
  VENTILATION: 'VENTILATION',
  MISTING: 'MISTING',
  WATER_CHANGING: 'WATER_CHANGING',
} as const
