/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { PlantCreateRequestDtoLocation } from './plantCreateRequestDtoLocation'
import type { PlantCreateRequestDtoPotType } from './plantCreateRequestDtoPotType'

export interface PlantCreateRequestDto {
  location: PlantCreateRequestDtoLocation
  nickname?: string
  plantingDate: string
  /**
   * @minLength 2
   * @maxLength 20
   */
  plantType: string
  /**
   * @minLength 2
   * @maxLength 20
   */
  potType: PlantCreateRequestDtoPotType
}
