/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { PostImageResponse } from './postImageResponse'
import type { UserResponse } from './userResponse'

export interface PostResponse {
  categoryId: number
  categoryName: string
  commentCount: number
  content: string
  createdAt: string
  id: number
  isLike: boolean
  likeCount: number
  postImages: PostImageResponse[]
  title: string
  updatedAt: string
  user: UserResponse
}
