/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type SignupRequestDtoSignupType = (typeof SignupRequestDtoSignupType)[keyof typeof SignupRequestDtoSignupType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignupRequestDtoSignupType = {
  EMAIL: 'EMAIL',
  SOCIAL: 'SOCIAL',
} as const
