/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type SignupRequestDtoRole = (typeof SignupRequestDtoRole)[keyof typeof SignupRequestDtoRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignupRequestDtoRole = {
  MEMBER: 'MEMBER',
  GUEST: 'GUEST',
  ADMIN: 'ADMIN',
} as const
