/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */

export type SignupRequestDtoGardeningExperience =
  (typeof SignupRequestDtoGardeningExperience)[keyof typeof SignupRequestDtoGardeningExperience]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SignupRequestDtoGardeningExperience = {
  BEGINNER: 'BEGINNER',
  INTERMEDIATE: 'INTERMEDIATE',
  EXPERT: 'EXPERT',
} as const
