/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Greeing OpenAPI3 UI
 * OpenAPI3 - Greeing Swagger UI
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateUserResponseRole } from './updateUserResponseRole'

export interface UpdateUserResponse {
  email: string
  nickname: string
  role: UpdateUserResponseRole
  userId: number
}
