const LINE_HEIGHT = '1.5'
const LETTER_SPACING = '0.01em'
const FONT_WEIGHT = {
  regular: 400,
  medium: 500,
  semiBold: 600,
  bold: 700,
  extraBold: 800,
}

export const FONT = {
  pretendard: 'Pretendard',
}

export const TYPOGRAPHY = {
  Regular10: {
    fontSize: '1rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium10: {
    fontSize: '1rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold10: {
    fontSize: '1rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold10: {
    fontSize: '1rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold10: {
    fontSize: '1rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular11: {
    fontSize: '1.1rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium11: {
    fontSize: '1.1rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold11: {
    fontSize: '1.1rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold11: {
    fontSize: '1.1rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold11: {
    fontSize: '1.1rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular12: {
    fontSize: '1.2rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium12: {
    fontSize: '1.2rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold12: {
    fontSize: '1.2rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold12: {
    fontSize: '1.2rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold12: {
    fontSize: '1.2rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular13: {
    fontSize: '1.3rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium13: {
    fontSize: '1.3rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold13: {
    fontSize: '1.3rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold13: {
    fontSize: '1.3rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold13: {
    fontSize: '1.3rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular14: {
    fontSize: '1.4rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium14: {
    fontSize: '1.4rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold14: {
    fontSize: '1.4rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold14: {
    fontSize: '1.4rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold14: {
    fontSize: '1.4rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular15: {
    fontSize: '1.5rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium15: {
    fontSize: '1.5rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold15: {
    fontSize: '1.5rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold15: {
    fontSize: '1.5rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold15: {
    fontSize: '1.5rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular16: {
    fontSize: '1.6rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium16: {
    fontSize: '1.6rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold16: {
    fontSize: '1.6rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold16: {
    fontSize: '1.6rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold16: {
    fontSize: '1.6rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular17: {
    fontSize: '1.7rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium17: {
    fontSize: '1.7rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold17: {
    fontSize: '1.7rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold17: {
    fontSize: '1.7rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold17: {
    fontSize: '1.7rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular18: {
    fontSize: '1.8rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium18: {
    fontSize: '1.8rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold18: {
    fontSize: '1.8rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold18: {
    fontSize: '1.8rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold18: {
    fontSize: '1.8rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular19: {
    fontSize: '1.9rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium19: {
    fontSize: '1.9rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold19: {
    fontSize: '1.9rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold19: {
    fontSize: '1.9rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold19: {
    fontSize: '1.9rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular20: {
    fontSize: '2rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium20: {
    fontSize: '2rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold20: {
    fontSize: '2rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold20: {
    fontSize: '2rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold20: {
    fontSize: '2rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular21: {
    fontSize: '2.1rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium21: {
    fontSize: '2.1rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold21: {
    fontSize: '2.1rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold21: {
    fontSize: '2.1rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold21: {
    fontSize: '2.1rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular22: {
    fontSize: '2.2rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium22: {
    fontSize: '2.2rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold22: {
    fontSize: '2.2rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold22: {
    fontSize: '2.2rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold22: {
    fontSize: '2.2rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular23: {
    fontSize: '2.3rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium23: {
    fontSize: '2.3rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold23: {
    fontSize: '2.3rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold23: {
    fontSize: '2.3rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold23: {
    fontSize: '2.3rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular24: {
    fontSize: '2.4rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium24: {
    fontSize: '2.4rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold24: {
    fontSize: '2.4rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold24: {
    fontSize: '2.4rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold24: {
    fontSize: '2.4rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular25: {
    fontSize: '2.5rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium25: {
    fontSize: '2.5rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold25: {
    fontSize: '2.5rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold25: {
    fontSize: '2.5rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold25: {
    fontSize: '2.5rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular26: {
    fontSize: '2.6rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium26: {
    fontSize: '2.6rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold26: {
    fontSize: '2.6rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold26: {
    fontSize: '2.6rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold26: {
    fontSize: '2.6rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular27: {
    fontSize: '2.7rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium27: {
    fontSize: '2.7rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold27: {
    fontSize: '2.7rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold27: {
    fontSize: '2.7rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold27: {
    fontSize: '2.7rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular28: {
    fontSize: '2.8rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium28: {
    fontSize: '2.8rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold28: {
    fontSize: '2.8rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold28: {
    fontSize: '2.8rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold28: {
    fontSize: '2.8rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular29: {
    fontSize: '2.9rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium29: {
    fontSize: '2.9rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold29: {
    fontSize: '2.9rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold29: {
    fontSize: '2.9rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold29: {
    fontSize: '2.9rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Regular30: {
    fontSize: '3rem',
    fontWeight: FONT_WEIGHT.regular,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Medium30: {
    fontSize: '3rem',
    fontWeight: FONT_WEIGHT.medium,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  SemiBold30: {
    fontSize: '3rem',
    fontWeight: FONT_WEIGHT.semiBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  Bold30: {
    fontSize: '3rem',
    fontWeight: FONT_WEIGHT.bold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
  ExtraBold30: {
    fontSize: '3rem',
    fontWeight: FONT_WEIGHT.extraBold,
    lineHeight: LINE_HEIGHT,
    letterSpacing: LETTER_SPACING,
  },
} as const
